### ISSUE TITLE
Thunderpush and CORS

### ISSUE THREAD

**Issue by jl2035** [thunderpush/thunderpush#41]
Let's say I have my django application under www.example.com/someapp
If I want the javascript from that app to connect to www.example.com:8900 (that's where I run Thunderpush), I get the "Cross-Origin Request Blocked" error.

Now I'm not sure what to do. I added CORS support to django, but that didn't fix anything. I think I have to enable that on the Thunderpush side. Am I thinking in the right way?

**Comment by kjagiello** [comment]
A workaround would be to use your web server as a reverse proxy. Here comes a nginx config example:

```
upstream thunders {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name         thunder.example.com;
    location / {
        proxy_pass http://thunders/;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass_header Server;
    }
}
```

**Comment by jl2035** [comment]
sorry.. I don't think I understand this line:

proxy_pass http://thunders/;

should there be anything on that url?

**Comment by jl2035** [comment]
Thanks. I got it working with this configuration:

    upstream thunderpush {
        server 127.0.0.1:8900;
    }

    location /thunderpush/ {
         proxy_pass http://thunderpush/;
         proxy_set_header X-Scheme $scheme;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
         proxy_set_header Host $http_host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-NginX-Proxy true;
         proxy_redirect off;
    }

**Comment by kjagiello** [comment]
Great to hear it!
