### ISSUE TITLE
Can it be deployed in multiple Tornado Processes?

### ISSUE THREAD

**Issue by danigosa** [thunderpush/thunderpush#42]
Can ThunderPus be deployed in several tornado processes and multiplex requests through Nginx? Or the Messenger registered by one Tornado process (and IOLoop) will not broadcast to others subscribed on a different process? I understand that it's not possible looking at the code, we're looking for a tornado push service but asking us if its possible to build a more flexible pusher that single-process one (and more scalable, indeed).

**Comment by kjagiello** [comment]
No, it wouldn't work, unfortunately. We would need to change the core architecture a bit to make it possible. Ideally, you would want ability to spawn multiple API processes, that receive messages, send them to a routing service that keeps information about who is connected to which push-server and then dispatch the message to a specific push server. 

I've been planning to implement this for a while, but I would like to discuss a bit about other ways to crack this problem. My goal is to keep Thunderpush as simple as possible (avoid extra dependencies and so on), as it is now, but at the same time allow customisation for more advanced use cases like this one.
