### ISSUE TITLE
Can't redirect stdout to a log file

### ISSUE THREAD

**Issue by marianoarga** [thunderpush/thunderpush#44]
Could you please provide a way to write the debug info into a file?, I need to monitor the server with a log file.

Thank you.

**Comment by kjagiello** [comment]
How did you deploy your thunderpush instance? If your are using [supervisor](http://supervisord.org/), then you could use the `stdout_logfile` configuration option to redirect the output from thunderpush to a file.

**Comment by marianoarga** [comment]
I have solved this when I realize that Thunderpush is writing debug to stderr and not to stdout.
And yes, I use supervisor.
Thank you.
